-- Create majors table
CREATE TABLE IF NOT EXISTS public.majors (
  id SERIAL PRIMARY KEY,
  major_name TEXT NOT NULL,
  major_code TEXT NOT NULL UNIQUE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Create index for faster lookups
CREATE INDEX IF NOT EXISTS majors_major_code_idx ON public.majors(major_code);
CREATE INDEX IF NOT EXISTS majors_major_name_idx ON public.majors(major_name);

-- Add comments
COMMENT ON TABLE public.majors IS 'University majors catalog with major codes';
COMMENT ON COLUMN public.majors.major_code IS 'Major code abbreviation (e.g., ACCT, BIOL)';
COMMENT ON COLUMN public.majors.major_name IS 'Full major name';

-- Insert all majors
INSERT INTO public.majors (major_name, major_code) VALUES
('Accounting', 'ACCT'),
('Aerospace Studies', 'AIRS'),
('American Sign Language', 'ASL'),
('Anatomical Sciences & Neurobiology', 'ASNB'),
('Anthropology', 'ANTH'),
('Applied Engineering', 'AE'),
('Applied Family Science', 'AFS'),
('Arabic', 'ARAB'),
('Art (Studio)', 'ART'),
('Art History', 'ARTH'),
('Asian Studies', 'AST'),
('Biochemistry', 'BIOC'),
('Bioengineering', 'BE'),
('Biology', 'BIOL'),
('Business', 'BUS'),
('Business Statistics', 'BSTA'),
('Campus Culture / Business', 'CAMP'),
('Chemical Engineering', 'CHE'),
('Chemistry', 'CHEM'),
('Chinese', 'CHNS'),
('Chinese Studies', 'CHST'),
('Civil & Environmental Engineering', 'CEE'),
('Commercial Law', 'CLAW'),
('Communication', 'COMM'),
('Communicative Disorders', 'CMDS'),
('Computer Science & Engineering', 'CSE'),
('Computer Information Systems', 'CIS'),
('Criminal Justice', 'CJ'),
('Criminalistics & Criminology', 'CC'),
('Critical & Curatorial Studies', 'CCS'),
('Dental Hygiene Education', 'DHED'),
('Design', 'DES'),
('Economics', 'ECON'),
('Education: Advanced Practitioner', 'EDAP'),
('Education: Leadership, Evaluation & Org. Development', 'LEAD'),
('Education: Special Education', 'EDSP'),
('Education: Teacher Preparation', 'EDTP'),
('Educational & Counseling Psychology', 'ECPY'),
('Electrical & Computer Engineering', 'ECE'),
('Engineering Fundamentals', 'ENGR'),
('Engineering Management', 'EM'),
('English', 'ENGL'),
('Entrepreneurship', 'ENTR'),
('Equine Administration', 'EQIN'),
('Exercise Physiology', 'EXP'),
('Environmental Sciences', 'ENVS'),
('Finance', 'FIN'),
('French', 'FREN'),
('General Studies', 'GEN'),
('General Studies', 'GNST'),
('Geography', 'GEOG'),
('German', 'GER'),
('Global Public Health', 'GLPH'),
('Greek', 'GR'),
('Health & Sport Sciences', 'HSS'),
('Hebrew', 'HEBR'),
('History', 'HIST'),
('Honors', 'HON'),
('Hospitality Management', 'HOSP'),
('Humanities', 'HUM'),
('Industrial and Systems Engineering', 'ISE'),
('Interpreter Training', 'ITP'),
('Japanese Language', 'JAPN'),
('Japanese Studies', 'JPST'),
('Justice Administration', 'JA'),
('Latin', 'LAT'),
('Latin American & Latino Studies', 'LALS'),
('Liberal Studies', 'LBST'),
('Linguistics', 'LING'),
('Management', 'MGMT'),
('Marketing', 'MKT'),
('Math/Pathways', 'MAT'),
('Mathematics', 'MATH'),
('Mechanical Engineering', 'ME'),
('Military Science', 'MILS'),
('Modern Languages', 'M L'),
('Music', 'MUS'),
('Music-Applied', 'MUSA'),
('Music Education', 'MUED'),
('Music History', 'MUH'),
('Music Therapy', 'MUTH'),
('Nursing', 'NURS'),
('Pan-African Studies', 'PAS'),
('Peace, Justice & Conflict Transformation', 'PEAC'),
('Pharmacology & Toxicology', 'PHTX'),
('Philosophy', 'PHIL'),
('Philosophy, Politics, & Economics', 'PPE'),
('Physics & Astronomy', 'PHYS'),
('Physiology', 'PHZB'),
('Planning', 'PLAN'),
('Political Science', 'POLS'),
('Portuguese', 'PORT'),
('Psychology', 'PSYC'),
('Public Administration', 'PADM'),
('Public Health, Epidemiology', 'PHEP'),
('Public Health, Biostatistics', 'PHST'),
('Public Health, Health Promotion & Behavioral Science', 'PHPB'),
('Public Health, Environmental Health', 'PHEH'),
('Public Health, Management Systems Sciences', 'PHMS'),
('Public Health, Public Health', 'PHPH'),
('Russian', 'RUSS'),
('Social Change', 'SCHG'),
('Social Work', 'BSW'),
('Sociology', 'SOC'),
('Spanish', 'SPAN'),
('Sport Administration', 'SPAD'),
('Theatre Arts', 'TA'),
('Urban Studies', 'URBS'),
('Women''s, Gender & Sexuality Studies', 'WGST')
ON CONFLICT (major_code) DO NOTHING;

